import { MultipleChoiceQuestion } from "./MutlipleChoiceSingleType";

export const MULTIPLE_CHOICE_QUESTIONS: MultipleChoiceQuestion[] = [
  {
    id: 1,
    audioText: "The capital city of France is a major cultural hub.",
    question: "What is the capital city of France?",
    options: [
      { id: "A", text: "London", isCorrect: false },
      { id: "B", text: "Paris", isCorrect: true },
      { id: "C", text: "Berlin", isCorrect: false },
      { id: "D", text: "Madrid", isCorrect: false },
    ],
    title: "",
    difficulty: "Beginner",
    category: "",
    tags: [],
    isNew: false,
    isMarked: false,
    pracStatus: "Undone",
    hasExplanation: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 2,
    audioText: "The largest planet in our solar system has a prominent ring system.",
    question: "Which is the largest planet in our solar system?",
    options: [
      { id: "A", text: "Earth", isCorrect: false },
      { id: "B", text: "Jupiter", isCorrect: true },
      { id: "C", text: "Mars", isCorrect: false },
      { id: "D", text: "Saturn", isCorrect: false },
    ],
    title: "",
    difficulty: "Beginner",
    category: "",
    tags: [],
    isNew: false,
    isMarked: false,
    pracStatus: "Undone",
    hasExplanation: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 3,
    audioText: "This river is the longest in South America.",
    question: "Which river is the longest in South America?",
    options: [
      { id: "A", text: "Nile", isCorrect: false },
      { id: "B", text: "Amazon", isCorrect: true },
      { id: "C", text: "Mississippi", isCorrect: false },
      { id: "D", text: "Yangtze", isCorrect: false },
    ],
    title: "",
    difficulty: "Beginner",
    category: "",
    tags: [],
    isNew: false,
    isMarked: false,
    pracStatus: "Undone",
    hasExplanation: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 4,
    audioText: "The invention of the telephone revolutionized communication.",
    question: "Who invented the telephone?",
    options: [
      { id: "A", text: "Thomas Edison", isCorrect: false },
      { id: "B", text: "Alexander Graham Bell", isCorrect: true },
      { id: "C", text: "Nikola Tesla", isCorrect: false },
      { id: "D", text: "Guglielmo Marconi", isCorrect: false },
    ],
    title: "",
    difficulty: "Beginner",
    category: "",
    tags: [],
    isNew: false,
    isMarked: false,
    pracStatus: "Undone",
    hasExplanation: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 5,
    audioText: "This animal is known as the king of the jungle.",
    question: "Which animal is known as the king of the jungle?",
    options: [
      { id: "A", text: "Tiger", isCorrect: false },
      { id: "B", text: "Lion", isCorrect: true },
      { id: "C", text: "Elephant", isCorrect: false },
      { id: "D", text: "Bear", isCorrect: false },
    ],
    title: "",
    difficulty: "Beginner",
    category: "",
    tags: [],
    isNew: false,
    isMarked: false,
    pracStatus: "Undone",
    hasExplanation: false,
    createdAt: "",
    updatedAt: "",
  },
];