import { MultipleChoiceQuestion } from "./MutlipleChoiceSingleType";

export const MULTIPLE_CHOICE_QUESTIONS: MultipleChoiceQuestion[] = [
  {
      id: 1,
      audioText: 'The capital city of France is a major cultural hub.',
      question: 'What is the capital city of France?',
      options: ['London', 'Paris', 'Berlin', 'Madrid'],
      correctAnswer: 1,
      title: "",
      difficulty: "Beginner",
      category: "",
      tags: [],
      isNew: false,
      isMarked: false,
      pracStatus: "Undone",
      hasExplanation: false,
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 2,
      audioText: 'The largest planet in our solar system has a prominent ring system.',
      question: 'Which is the largest planet in our solar system?',
      options: ['Earth', 'Jupiter', 'Mars', 'Saturn'],
      correctAnswer: 1,
      title: "",
      difficulty: "Beginner",
      category: "",
      tags: [],
      isNew: false,
      isMarked: false,
      pracStatus: "Undone",
      hasExplanation: false,
      createdAt: "",
      updatedAt: ""
  },
  // ... (Additional 53 questions follow, truncated for brevity)
  {
      id: 3,
      audioText: 'This river is the longest in South America.',
      question: 'Which river is the longest in South America?',
      options: ['Nile', 'Amazon', 'Mississippi', 'Yangtze'],
      correctAnswer: 1,
      title: "",
      difficulty: "Beginner",
      category: "",
      tags: [],
      isNew: false,
      isMarked: false,
      pracStatus: "Undone",
      hasExplanation: false,
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 4,
      audioText: 'The invention of the telephone revolutionized communication.',
      question: 'Who invented the telephone?',
      options: ['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Guglielmo Marconi'],
      correctAnswer: 1,
      title: "",
      difficulty: "Beginner",
      category: "",
      tags: [],
      isNew: false,
      isMarked: false,
      pracStatus: "Undone",
      hasExplanation: false,
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 5,
      audioText: 'This animal is known as the king of the jungle.',
      question: 'Which animal is known as the king of the jungle?',
      options: ['Tiger', 'Lion', 'Elephant', 'Bear'],
      correctAnswer: 1,
      title: "",
      difficulty: "Beginner",
      category: "",
      tags: [],
      isNew: false,
      isMarked: false,
      pracStatus: "Undone",
      hasExplanation: false,
      createdAt: "",
      updatedAt: ""
  },
];