import {AudioTopic } from '../../common/types';
export const audioTopics: AudioTopic[] = [
  {
    id: 1,
    title: 'Introduction to Biology',
    duration: '00:40',
    speaker: 'Dr. Smith',
    difficulty: 'Beginner',
    link: '/audio/intro-to-biology.mp3',
    type: 'lecture',
    preparationTime: 10,
    recordingTime: 40,
    category: 'Science',
    tags: ['biology', 'introduction', 'basics'],
    isNew: true,
    isMarked: false,
    pracStatus: 'Undone',
    hasExplanation: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
    questionType: 'ASQ'
  },
  {
    id: 2,
    title: 'World War II History',
    duration: '00:40',
    speaker: 'Prof. Johnson',
    difficulty: 'Intermediate',
    link: '/audio/wwii-history.mp3',
    type: 'lecture',
    preparationTime: 10,
    recordingTime: 40,
    category: 'History',
    tags: ['history', 'war', 'world war'],
    isNew: false,
    isMarked: true,
    pracStatus: 'In Progress',
    hasExplanation: true,
    createdAt: '2024-01-10',
    updatedAt: '2024-01-20',
    questionType: 'ASQ'
  },
  {
    id: 3,
    title: 'Climate Change Science',
    duration: '00:40',
    speaker: 'Dr. Wilson',
    difficulty: 'Advanced',
    link: '/audio/climate-change.mp3',
    type: 'lecture',
    preparationTime: 10,
    recordingTime: 40,
    category: 'Environmental Science',
    tags: ['climate', 'environment', 'science'],
    isNew: true,
    isMarked: false,
    pracStatus: 'Undone',
    hasExplanation: false,
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
    questionType: 'ASQ'
  },
  {
    id: 4,
    title: 'Shakespeare Literature',
    duration: '00:40',
    speaker: 'Prof. Brown',
    difficulty: 'Intermediate',
    link: '/audio/shakespeare.mp3',
    type: 'lecture',
    preparationTime: 10,
    recordingTime: 40,
    category: 'Literature',
    tags: ['shakespeare', 'literature', 'english'],
    isNew: false,
    isMarked: false,
    pracStatus: 'Done',
    hasExplanation: true,
    createdAt: '2024-01-05',
    updatedAt: '2024-01-15',
    questionType: 'ASQ'
  },
  {
    id: 5,
    title: 'Quantum Physics Basics',
    duration: '00:40',
    speaker: 'Dr. Davis',
    difficulty: 'Advanced',
    link: '/audio/quantum-physics.mp3',
    type: 'lecture',
    preparationTime: 10,
    recordingTime: 40,
    category: 'Physics',
    tags: ['physics', 'quantum', 'advanced'],
    isNew: false,
    isMarked: true,
    pracStatus: 'Undone',
    hasExplanation: true,
    createdAt: '2024-01-08',
    updatedAt: '2024-01-12',
    questionType: 'ASQ'
  },
  {
    id: 6,
    title: 'Economic Principles',
    duration: '00:40',
    speaker: 'Prof. Miller',
    difficulty: 'Beginner',
    link: '/audio/economic-principles.mp3',
    type: 'lecture',
    preparationTime: 10,
    recordingTime: 40,
    category: 'Economics',
    tags: ['economics', 'principles', 'basics'],
    isNew: true,
    isMarked: false,
    pracStatus: 'In Progress',
    hasExplanation: false,
    createdAt: '2024-01-20',
    updatedAt: '2024-01-22',
    questionType: 'ASQ'
  },
  {
    id: 7,
    title: 'Art History Renaissance',
    duration: '00:40',
    speaker: 'Dr. Taylor',
    difficulty: 'Intermediate',
    link: '/audio/art-history.mp3',
    type: 'lecture',
    preparationTime: 10,
    recordingTime: 40,
    category: 'Art History',
    tags: ['art', 'renaissance', 'history'],
    isNew: false,
    isMarked: false,
    pracStatus: 'Done',
    hasExplanation: true,
    createdAt: '2024-01-03',
    updatedAt: '2024-01-10',
    questionType: 'ASQ'
  },
  {
    id: 8,
    title: 'Psychology Fundamentals',
    duration: '00:40',
    speaker: 'Prof. Anderson',
    difficulty: 'Beginner',
    link: '/audio/psychology.mp3',
    type: 'lecture',
    preparationTime: 10,
    recordingTime: 40,
    category: 'Psychology',
    tags: ['psychology', 'fundamentals', 'behavior'],
    isNew: false,
    isMarked: true,
    pracStatus: 'Undone',
    hasExplanation: true,
    createdAt: '2024-01-12',
    updatedAt: '2024-01-18',
    questionType: 'ASQ'
  },
];