import { RepeatSentenceFeedback, RepeatSentenceQuestion } from "./RepeatSentenceTypes";


export const REPEAT_SENTENCE_QUESTIONS: RepeatSentenceQuestion[] = [
  {
      id: 1,
      audio: 'The weather is sunny today.',
      difficulty: 'Beginner',
      category: 'Daily Life',
      tags: ['weather', 'easy'],
      expectedAnswer: 'Repeat with clear pronunciation.',
      isNew: false,
      isMarked: false,
      pracStatus: 'Undone',
      hasExplanation: true,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 2,
      audio: 'Technology advances rapidly in modern society.',
      difficulty: 'Intermediate',
      category: 'Technology',
      tags: ['tech', 'medium'],
      expectedAnswer: 'Focus on pacing and word accuracy.',
      isNew: true,
      isMarked: true,
      pracStatus: 'In Progress',
      hasExplanation: false,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 3,
      audio: 'Quantum physics explores the behavior of subatomic particles.',
      difficulty: 'Advanced',
      category: 'Science',
      tags: ['physics', 'hard'],
      expectedAnswer: 'Emphasize technical terms.',
      isNew: false,
      isMarked: false,
      pracStatus: 'Done',
      hasExplanation: true,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 4,
      audio: 'Cultural festivals celebrate diversity worldwide.',
      difficulty: 'Beginner',
      category: 'Culture',
      tags: ['festivals', 'easy'],
      expectedAnswer: 'Maintain a lively tone.',
      isNew: true,
      isMarked: true,
      pracStatus: 'Undone',
      hasExplanation: false,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 5,
      audio: 'Economic policies influence global markets significantly.',
      difficulty: 'Intermediate',
      category: 'Economics',
      tags: ['economy', 'medium'],
      expectedAnswer: 'Ensure smooth fluency.',
      isNew: false,
      isMarked: false,
      pracStatus: 'In Progress',
      hasExplanation: true,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 6,
      audio: 'Artificial intelligence transforms healthcare innovations.',
      difficulty: 'Advanced',
      category: 'Health',
      tags: ['AI', 'hard'],
      expectedAnswer: 'Pronounce "artificial intelligence" clearly.',
      isNew: true,
      isMarked: true,
      pracStatus: 'Done',
      hasExplanation: false,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 7,
      audio: 'The ocean contains vast unexplored ecosystems.',
      difficulty: 'Beginner',
      category: 'Nature',
      tags: ['ocean', 'easy'],
      expectedAnswer: 'Use a calm tone.',
      isNew: false,
      isMarked: false,
      pracStatus: 'Undone',
      hasExplanation: true,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 8,
      audio: 'Sustainable energy reduces carbon emissions effectively.',
      difficulty: 'Intermediate',
      category: 'Environment',
      tags: ['sustainability', 'medium'],
      expectedAnswer: 'Stress key terms.',
      isNew: true,
      isMarked: true,
      pracStatus: 'In Progress',
      hasExplanation: false,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 9,
      audio: 'Neuroscience studies the complexity of human brains.',
      difficulty: 'Advanced',
      category: 'Science',
      tags: ['neuroscience', 'hard'],
      expectedAnswer: 'Focus on scientific accuracy.',
      isNew: false,
      isMarked: false,
      pracStatus: 'Done',
      hasExplanation: true,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 10,
      audio: 'Music therapy improves mental health outcomes.',
      difficulty: 'Beginner',
      category: 'Health',
      tags: ['music', 'easy'],
      expectedAnswer: 'Add a rhythmic flow.',
      isNew: true,
      isMarked: true,
      pracStatus: 'Undone',
      hasExplanation: false,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 11,
      audio: 'Global trade impacts economic growth annually.',
      difficulty: 'Intermediate',
      category: 'Economics',
      tags: ['trade', 'medium'],
      expectedAnswer: 'Maintain steady pace.',
      isNew: false,
      isMarked: false,
      pracStatus: 'In Progress',
      hasExplanation: true,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 12,
      audio: 'Astronomy reveals secrets of distant galaxies.',
      difficulty: 'Advanced',
      category: 'Space',
      tags: ['astronomy', 'hard'],
      expectedAnswer: 'Pronounce complex words clearly.',
      isNew: true,
      isMarked: true,
      pracStatus: 'Done',
      hasExplanation: false,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
];


 
export const MOCK_FEEDBACK: { [key: number]: RepeatSentenceFeedback } = {
  1: {
    overallScore: 85,
    pronunciation: 90,
    fluency: 80,
    content: 85,
    wordsRepeated: 5,
    totalWords: 5,
    feedback: ['Clear pronunciation of key words.', 'Good attempt at intonation.'],
    improvements: ['Improve pacing for better fluency.', 'Avoid omitting small words.'],
  },
  2: {
    overallScore: 70,
    pronunciation: 65,
    fluency: 75,
    content: 70,
    wordsRepeated: 6,
    totalWords: 7,
    feedback: ['Decent pacing observed.', 'Some words were clear.'],
    improvements: ['Work on pronunciation accuracy.', 'Reduce hesitations.'],
  },
  3: {
    overallScore: 90,
    pronunciation: 95,
    fluency: 85,
    content: 90,
    wordsRepeated: 8,
    totalWords: 8,
    feedback: ['Excellent technical term usage.', 'Smooth delivery.'],
    improvements: ['Maintain consistency throughout.'],
  },
  4: {
    overallScore: 80,
    pronunciation: 85,
    fluency: 75,
    content: 80,
    wordsRepeated: 4,
    totalWords: 5,
    feedback: ['Lively tone was engaging.', 'Good word choice.'],
    improvements: ['Repeat all words accurately.', 'Improve fluency.'],
  },
  5: {
    overallScore: 75,
    pronunciation: 70,
    fluency: 80,
    content: 75,
    wordsRepeated: 5,
    totalWords: 6,
    feedback: ['Smooth flow in parts.', 'Clear key terms.'],
    improvements: ['Avoid missing words.', 'Enhance pronunciation.'],
  },
  6: {
    overallScore: 88,
    pronunciation: 90,
    fluency: 85,
    content: 88,
    wordsRepeated: 6,
    totalWords: 6,
    feedback: ['Clear "artificial intelligence" pronunciation.', 'Good rhythm.'],
    improvements: ['Slightly faster delivery.'],
  },
  7: {
    overallScore: 82,
    pronunciation: 85,
    fluency: 80,
    content: 80,
    wordsRepeated: 5,
    totalWords: 5,
    feedback: ['Calm tone was appropriate.', 'Clear enunciation.'],
    improvements: ['Maintain pace consistency.'],
  },
  8: {
    overallScore: 78,
    pronunciation: 75,
    fluency: 80,
    content: 78,
    wordsRepeated: 6,
    totalWords: 7,
    feedback: ['Good emphasis on key terms.', 'Steady pace.'],
    improvements: ['Improve word accuracy.', 'Work on fluency.'],
  },
  9: {
    overallScore: 92,
    pronunciation: 95,
    fluency: 90,
    content: 90,
    wordsRepeated: 7,
    totalWords: 7,
    feedback: ['Excellent scientific accuracy.', 'Smooth delivery.'],
    improvements: ['None significant.'],
  },
  10: {
    overallScore: 84,
    pronunciation: 88,
    fluency: 80,
    content: 85,
    wordsRepeated: 5,
    totalWords: 5,
    feedback: ['Rhythmic flow was good.', 'Clear delivery.'],
    improvements: ['Enhance intonation variation.'],
  },
  11: {
    overallScore: 76,
    pronunciation: 70,
    fluency: 80,
    content: 75,
    wordsRepeated: 5,
    totalWords: 6,
    feedback: ['Steady pace in parts.', 'Clear key terms.'],
    improvements: ['Avoid missing words.', 'Improve pronunciation.'],
  },
  12: {
    overallScore: 89,
    pronunciation: 92,
    fluency: 85,
    content: 90,
    wordsRepeated: 6,
    totalWords: 6,
    feedback: ['Clear complex words.', 'Good rhythm.'],
    improvements: ['Slightly faster delivery.'],
  },
};



export const instructionsSections = [
    {
        title: 'Task Overview',
        items: ['Listen to the sentence and repeat it exactly as you heard it.'],
    },
    {
        title: 'Time Allocation',
        items: ['Audio plays automatically', 'Recording: 15 seconds'],
    },
    {
        title: 'Tips',
        items: [
            'Listen carefully to every word',
            'Repeat immediately after audio',
            'Maintain the same intonation',
            'Don\'t add or omit words',
        ],
    },
    {
        title: 'Scoring',
        items: [
            'Content: All words repeated',
            'Pronunciation: Accuracy',
            'Fluency: Natural flow',
        ],
    },
];
