import { ReadAloudQuestion } from "./ReadAloudTypes";

export const readAloudQuestions: ReadAloudQuestion[] = [
  {
      id: 1,
      text: 'Climate change is a pressing global issue. Scientists are researching its impacts, such as melting ice caps, rising sea levels, and extreme weather. Immediate action from governments and individuals is essential to reduce emissions.',
      preparationTime: 40,
      recordingTime: 40,
      difficulty: 'Intermediate',
      category: 'Environmental Science',
      tags: ['climate', 'environment', 'science'],
      expectedAnswer: 'Read the text clearly, emphasizing key terms like "climate change" and "emissions."',
      isNew: false,
      isMarked: false,
      pracStatus: 'Undone',
      hasExplanation: true,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 2,
      text: 'Artificial intelligence is transforming industries like healthcare and transportation. Machine learning enhances efficiency, but raises concerns about job displacement and ethics.',
      preparationTime: 40,
      recordingTime: 40,
      difficulty: 'Advanced',
      category: 'Technology',
      tags: ['AI', 'technology', 'ethics'],
      expectedAnswer: 'Pronounce technical terms like "artificial intelligence" accurately with a steady pace.',
      isNew: true,
      isMarked: true,
      pracStatus: 'In Progress',
      hasExplanation: false,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 3,
      text: 'Education shapes society’s future. Online platforms and virtual reality are making learning more accessible and interactive for students worldwide.',
      preparationTime: 40,
      recordingTime: 40,
      difficulty: 'Beginner',
      category: 'Education',
      tags: ['education', 'online learning', 'technology'],
      expectedAnswer: 'Read with enthusiasm, stressing words like "accessible" and "interactive."',
      isNew: false,
      isMarked: false,
      pracStatus: 'Done',
      hasExplanation: true,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 4,
      text: 'Renewable energy sources, such as solar and wind, are critical for sustainable development. They reduce reliance on fossil fuels and combat climate change.',
      preparationTime: 40,
      recordingTime: 40,
      difficulty: 'Intermediate',
      category: 'Energy',
      tags: ['renewable', 'sustainability', 'energy'],
      expectedAnswer: 'Read fluently, with clear enunciation of "renewable" and "sustainable."',
      isNew: true,
      isMarked: false,
      pracStatus: 'Undone',
      hasExplanation: false,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 5,
      text: 'The human brain is a complex organ responsible for thought, memory, and emotion. Neuroscience advances are uncovering its mysteries.',
      preparationTime: 40,
      recordingTime: 40,
      difficulty: 'Advanced',
      category: 'Science',
      tags: ['neuroscience', 'brain', 'biology'],
      expectedAnswer: 'Read with precision, emphasizing scientific terms like "neuroscience."',
      isNew: false,
      isMarked: true,
      pracStatus: 'In Progress',
      hasExplanation: true,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 6,
      text: 'Cultural diversity enriches societies by fostering understanding and innovation. Embracing differences promotes global harmony.',
      preparationTime: 40,
      recordingTime: 40,
      difficulty: 'Beginner',
      category: 'Culture',
      tags: ['diversity', 'culture', 'society'],
      expectedAnswer: 'Read with a warm tone, highlighting "diversity" and "harmony."',
      isNew: true,
      isMarked: false,
      pracStatus: 'Done',
      hasExplanation: false,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 7,
      text: 'Space exploration has led to technological breakthroughs, from satellites to medical imaging. Future missions aim to explore Mars and beyond.',
      preparationTime: 40,
      recordingTime: 40,
      difficulty: 'Intermediate',
      category: 'Space',
      tags: ['space', 'exploration', 'technology'],
      expectedAnswer: 'Read with curiosity, stressing "exploration" and "breakthroughs."',
      isNew: false,
      isMarked: true,
      pracStatus: 'Undone',
      hasExplanation: true,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
  {
      id: 8,
      text: 'Financial literacy empowers individuals to manage money wisely. Understanding budgeting and investing is key to economic stability.',
      preparationTime: 40,
      recordingTime: 40,
      difficulty: 'Beginner',
      category: 'Finance',
      tags: ['finance', 'literacy', 'economy'],
      expectedAnswer: 'Read clearly, emphasizing terms like "financial literacy" and "budgeting."',
      isNew: true,
      isMarked: false,
      pracStatus: 'In Progress',
      hasExplanation: false,
      title: "",
      createdAt: "",
      updatedAt: ""
  },
];