import { QuestionTopic } from '../../common/types';

export const questionTopics: QuestionTopic[] = [
  { 
    id: 1, 
    title: 'Basic Geography', 
    duration: '00:05', 
    speaker: 'Dr. Lee', 
    difficulty: 'Beginner', 
    link: '/audio/basic-geography-question.mp3',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'Geography',
    tags: ['geography', 'basic', 'location'],
    isNew: true,
    isMarked: false,
    pracStatus: 'Undone',
    hasExplanation: true,
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20'
  },
  { 
    id: 2, 
    title: 'Everyday Vocabulary', 
    duration: '00:04', 
    speaker: 'Prof. Adams', 
    difficulty: 'Beginner', 
    link: '/audio/everyday-vocabulary-question.mp3',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'Vocabulary',
    tags: ['vocabulary', 'everyday', 'words'],
    isNew: false,
    isMarked: true,
    pracStatus: 'Done',
    hasExplanation: false,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-18'
  },
  { 
    id: 3, 
    title: 'Historical Facts', 
    duration: '00:06', 
    speaker: 'Dr. Evans', 
    difficulty: 'Intermediate', 
    link: '/audio/historical-facts-question.mp3',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'History',
    tags: ['history', 'facts', 'dates'],
    isNew: true,
    isMarked: false,
    pracStatus: 'In Progress',
    hasExplanation: true,
    createdAt: '2024-01-22',
    updatedAt: '2024-01-22'
  },
  { 
    id: 4, 
    title: 'Science Basics', 
    duration: '00:05', 
    speaker: 'Prof. Carter', 
    difficulty: 'Intermediate', 
    link: '/audio/science-basics-question.mp3',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'Science',
    tags: ['science', 'basics', 'concepts'],
    isNew: false,
    isMarked: false,
    pracStatus: 'Undone',
    hasExplanation: true,
    createdAt: '2024-01-10',
    updatedAt: '2024-01-15'
  },
  { 
    id: 5, 
    title: 'Cultural Knowledge', 
    duration: '00:07', 
    speaker: 'Dr. Harris', 
    difficulty: 'Advanced', 
    link: '/audio/cultural-knowledge-question.mp3',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'Culture',
    tags: ['culture', 'knowledge', 'society'],
    isNew: false,
    isMarked: true,
    pracStatus: 'Done',
    hasExplanation: false,
    createdAt: '2024-01-08',
    updatedAt: '2024-01-12'
  },
  { 
    id: 6, 
    title: 'Math Concepts', 
    duration: '00:05', 
    speaker: 'Prof. Taylor', 
    difficulty: 'Intermediate', 
    link: '/audio/math-concepts-question.mp3',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'Mathematics',
    tags: ['math', 'concepts', 'numbers'],
    isNew: true,
    isMarked: false,
    pracStatus: 'Undone',
    hasExplanation: true,
    createdAt: '2024-01-25',
    updatedAt: '2024-01-25'
  },
  { 
    id: 7, 
    title: 'General Knowledge', 
    duration: '00:06', 
    speaker: 'Dr. Moore', 
    difficulty: 'Beginner', 
    link: '/audio/general-knowledge-question.mp3',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'General',
    tags: ['general', 'knowledge', 'facts'],
    isNew: false,
    isMarked: false,
    pracStatus: 'In Progress',
    hasExplanation: true,
    createdAt: '2024-01-18',
    updatedAt: '2024-01-20'
  },
  { 
    id: 8, 
    title: 'Environmental Awareness', 
    duration: '00:08', 
    speaker: 'Prof. Clark', 
    difficulty: 'Advanced', 
    link: '/audio/environmental-awareness-question.mp3',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'Environment',
    tags: ['environment', 'awareness', 'nature'],
    isNew: true,
    isMarked: true,
    pracStatus: 'Undone',
    hasExplanation: false,
    createdAt: '2024-01-23',
    updatedAt: '2024-01-23'
  },
];