import { QuestionTopic } from "./AnswerShortQuestionsTypes";

export const questionTopics: QuestionTopic[] = [
  {
    id: 1,
    title: 'Basic Geography',
    duration: '00:05',
    speaker: 'Dr. Lee',
    difficulty: 'Beginner',
    audioText: 'What is the capital city of France?',
    expectedAnswer: 'Paris',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'Geography',
    tags: ['geography', 'basic', 'location'],
    isNew: true,
    isMarked: false,
    pracStatus: 'Practice',
    hasExplanation: true,
    createdAt: '2025-06-01',
    updatedAt: '2025-06-01'
  },
  {
    id: 2,
    title: 'Everyday Vocabulary',
    duration: '00:04',
    speaker: 'Prof. Adams',
    difficulty: 'Beginner',
    audioText: 'What is the English word for a place where you buy bread and cakes?',
    expectedAnswer: 'Bakery',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'Vocabulary',
    tags: ['vocabulary', 'everyday', 'language'],
    isNew: false,
    isMarked: true,
    pracStatus: 'Done',
    hasExplanation: true,
    createdAt: '2025-05-30',
    updatedAt: '2025-06-05'
  },
  {
    id: 3,
    title: 'Historical Facts',
    duration: '00:06',
    speaker: 'Dr. Evans',
    difficulty: 'Intermediate',
    audioText: 'In which year did World War II end?',
    expectedAnswer: '1945',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 5,
    recordingTime: 10,
    category: 'History',
    tags: ['history', 'facts', 'events'],
    isNew: true,
    isMarked: false,
    pracStatus: 'In Progress',
    hasExplanation: true,
    createdAt: '2025-06-03',
    updatedAt: '2025-06-03'
  },
  {
    id: 4,
    title: 'Science Basics',
    duration: '00:05',
    speaker: 'Prof. Carter',
    difficulty: 'Intermediate',
    audioText: 'What gas do plants absorb from the atmosphere during photosynthesis?',
    expectedAnswer: 'Carbon dioxide',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 5,
    recordingTime: 10,
    category: 'Science',
    tags: ['science', 'basics', 'concepts'],
    isNew: false,
    isMarked: false,
    pracStatus: 'Practice',
    hasExplanation: true,
    createdAt: '2025-05-28',
    updatedAt: '2025-06-02'
  },
  {
    id: 5,
    title: 'Cultural Knowledge',
    duration: '00:07',
    speaker: 'Dr. Harris',
    difficulty: 'Advanced',
    audioText: 'What is the traditional Japanese tea ceremony called?',
    expectedAnswer: 'Chanoyu',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 4,
    recordingTime: 10,
    category: 'Culture',
    tags: ['culture', 'knowledge', 'traditions'],
    isNew: false,
    isMarked: true,
    pracStatus: 'Done',
    hasExplanation: false,
    createdAt: '2025-05-25',
    updatedAt: '2025-05-30'
  },
  {
    id: 6,
    title: 'Math Concepts',
    duration: '00:05',
    speaker: 'Prof. Taylor',
    difficulty: 'Intermediate',
    audioText: 'What is the value of pi, rounded to two decimal places?',
    expectedAnswer: '3.14',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 4,
    recordingTime: 10,
    category: 'Mathematics',
    tags: ['math', 'concepts', 'numbers'],
    isNew: true,
    isMarked: false,
    pracStatus: 'Practice',
    hasExplanation: true,
    createdAt: '2025-06-10',
    updatedAt: '2025-06-10'
  },
  {
    id: 7,
    title: 'General Knowledge',
    duration: '00:06',
    speaker: 'Dr. Moore',
    difficulty: 'Beginner',
    audioText: 'What is the largest planet in our solar system?',
    expectedAnswer: 'Jupiter',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 3,
    recordingTime: 10,
    category: 'General',
    tags: ['general', 'knowledge', 'facts'],
    isNew: false,
    isMarked: false,
    pracStatus: 'In Progress',
    hasExplanation: true,
    createdAt: '2025-06-02',
    updatedAt: '2025-06-05'
  },
  {
    id: 8,
    title: 'Environmental Awareness',
    duration: '00:08',
    speaker: 'Prof. Clark',
    difficulty: 'Advanced',
    audioText: 'What is the primary source of energy for Earth’s climate system?',
    expectedAnswer: 'Sun',
    type: 'question',
    questionType: 'ASQ',
    preparationTime: 4,
    recordingTime: 10,
    category: 'Environment',
    tags: ['environment', 'awareness', 'nature'],
    isNew: true,
    isMarked: true,
    pracStatus: 'Practice',
    hasExplanation: false,
    createdAt: '2025-06-07',
    updatedAt: '2025-06-07'
  },
];